"""update resources table

Revision ID: update_resources_table
Revises: 12bc348e9691
Create Date: 2025-02-07 01:49:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'update_resources_table'
down_revision = '12bc348e9691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('aws_region', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('aws_account_id', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('aws_resource_id', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('aws_resource_type', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('aws_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('resources', sa.Column('last_scan_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'last_scan_at')
    op.drop_column('resources', 'aws_tags')
    op.drop_column('resources', 'aws_resource_type')
    op.drop_column('resources', 'aws_resource_id')
    op.drop_column('resources', 'aws_account_id')
    op.drop_column('resources', 'aws_region')
    # ### end Alembic commands ###
